<?php

namespace HeimrichHannot\FlatpickrBundle\DataContainer;

use Contao\DataContainer;
use Contao\Form;
use Contao\Widget;

/**
 * @property Widget $widget
 * @property Form  $form
 */
class FlatpickrDataContainer extends DataContainer
{
    protected ?Widget $widget = null;
    protected ?Form $form = null;

    public function __construct(string $table, int $id)
    {
        $this->strTable = $table;
        $this->intId = $id;
    }

    public function getPalette()
    {
        return '';
    }

    protected function save($varValue)
    {
    }

    public function __get($strKey)
    {
        switch ($strKey) {
            case 'widget':
                return $this->widget;
            case 'form':
                return $this->form;
        }
        return parent::__get($strKey); // TODO: Change the autogenerated stub
    }

    public function __set($strKey, $varValue)
    {
        switch ($strKey) {
            case 'widget':
                $this->widget = $varValue;
                if (!$this->strField && $varValue instanceof Widget) {
                    $this->strField = $varValue->name;
                }
                break;
            case 'form':
                $this->form = $varValue;
        }
        parent::__set($strKey, $varValue); // TODO: Change the autogenerated stub
    }


}