huh_encore:
  js_entries:
    - { name: "contao-flatpickr-bundle", file: "vendor/heimrichhannot/contao-flatpickr-bundle/src/Resources/assets/js/contao-flatpickr-bundle-init.js" }
    - { name: "contao-flatpickr-bundle-theme", requires_css: true, file: "vendor/heimrichhannot/contao-flatpickr-bundle/src/Resources/assets/js/contao-flatpickr-bundle-theme.js" }
  unset_global_keys:
    js:
      - contao-flatpickr-bundle
      - contao-flatpickr-bundle--library
    css:
      - contao-flatpuckr-bundle