services:
  _defaults:
    public: true
    autowire: true

    # Hook Listener
  HeimrichHannot\FlatpickrBundle\EventListener\GetAttributesFromDcaListener: ~
  HeimrichHannot\FlatpickrBundle\EventListener\BeforeRenderWidgetListener:
    tags:
      - { name: kernel.event_listener, event: huh.twig.beforeRenderTemplate }

  HeimrichHannot\FlatpickrBundle\EventListener\AdjustFilterOptionsEventListener:
    tags:
      - { name: kernel.event_listener, event: huh.filter.event.adjust_filter_options_event, method: '__invoke' }

  HeimrichHannot\FlatpickrBundle\EventListener\LoadDataContainerListener: