services:
  HeimrichHannot\ContaoFlatpickrBundle\EventListener\BeforeRenderWidgetListener:
    autowire: true
    tags:
      - { name: kernel.event_listener, event: huh.twig.beforeRenderTemplate }
  HeimrichHannot\ContaoFlatpickrBundle\EventListener\AdjustFilterOptionsListener:
    autowire: true
    tags:
      - { name: kernel.event_listener, event: huh.filter.event.adjust_filter_options_event }