services:
  _defaults:
    public: true
    autowire: true

  huh.flatpickr.manager.flatpickr_manager:
    class: HeimrichHannot\FlatpickrBundle\Manager\FlatpickrManager
  HeimrichHannot\FlatpickrBundle\Manager\FlatpickrManager: '@huh.flatpickr.manager.flatpickr_manager'

  HeimrichHannot\FlatpickrBundle\:
    resource: "../../{Asset,Util}/*"
    autoconfigure: true